version: 2.1

orbs:
  win: circleci/windows@5.0

jobs:
  checkout_code:
    docker:
      - image: cimg/base:2022.08
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths:
            - .

  e2e_test:
    parameters:
      dotnet_version:
        type: string
    executor:
      name: win/default
    environment:
      ROOT_DIR: ${CIRCLE_WORKING_DIRECTORY}
      USE_NAT: true
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Install Dependencies
          command: dotnet restore
      - run:
          name: Build Solution
          command: dotnet build --configuration Development
      - run:
          name: Build DotNetCore Project
          command: |
            dotnet build "Aikido.Zen.DotNetCore/Aikido.Zen.DotNetCore.csproj" --configuration Development --framework << parameters.dotnet_version >>
      - run:
          name: Run E2E Tests
          command: |
            dotnet test "Aikido.Zen.Test.End2End/Aikido.Zen.Test.End2End.csproj" \
              --configuration Development \
              --verbosity detailed \
              --logger "console;verbosity=detailed" \
              --no-build \
              --no-restore

workflows:
  test_on_pr:
    jobs:
      - checkout_code
      - e2e_test:
          requires:
            - checkout_code
          matrix:
            parameters:
              dotnet_version: ["6.0", "7.0", "8.0"]
