version: 2.1

orbs:
  win: circleci/windows@5.0

jobs:
  checkout_code:
    docker:
      - image: cimg/base:2022.08
    steps:
      - checkout
      - run:
          name: Generate csproj Checksums
          command: |
            # Find all .csproj files, sort them, and generate a consistent checksum
            find . -type f -name "*.csproj" | sort | xargs sha256sum | awk '{print $1}' | sort | sha256sum | awk '{print $1}' > csproj-checksums.lock
      - persist_to_workspace:
          root: .
          paths:
            - .
            - csproj-checksums.lock

  e2e_test:
    parameters:
      dotnet_version:
        type: string
    executor:
      name: win/default
    environment:
      ROOT_DIR: ${CIRCLE_WORKING_DIRECTORY}
      USE_NAT: true
    steps:
      - attach_workspace:
          at: .
      - restore_cache:
          name: Restore NuGet Packages
          keys:
            - nuget-packages-{{ checksum "csproj-checksums.lock" }}
      - run:
          name: Restore NuGet Packages
          command: |
            nuget restore
      - run:
          name: Build .NET Framework Projects
          command: |
            $msbuildPath = "C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\MSBuild.exe"
            & $msbuildPath
      - run:
          name: Run E2E Tests
          command: |
            dotnet test "Aikido.Zen.Test.End2End/Aikido.Zen.Test.End2End.csproj" `
              --configuration Debug `
              --logger "console;verbosity=detailed" `
              --no-build `
              --no-restore  `
              tee test-output.log
      - save_cache:
          key: nuget-packages-{{ checksum "csproj-checksums.lock" }}
          paths:
            - ~/.nuget/packages
            - packages

workflows:
  test_on_pr:
    jobs:
      - checkout_code
      - e2e_test:
          requires:
            - checkout_code
          matrix:
            parameters:
              dotnet_version: ["6.0", "7.0", "8.0"]
