version: 2.1

jobs:
  checkout_code:
    docker:
      - image: cimg/base:2022.08
    steps:
      - checkout
      - run:
          name: Generate Package References Checksum
          command: bash ./.circleci/generate-packages-checksum.sh
      - persist_to_workspace:
          root: .
          paths:
            - .
            - packages.txt
            - packages.checksum

  e2e_test:
    parameters:
      dotnet_version:
        type: string
    machine:
      image: ubuntu-2204:current
    steps:
      - checkout
      - run:
          name: install dotnet
          command: |
            sudo apt-get update
            sudo apt-get install -y dotnet-sdk-<< parameters.dotnet_version >>
      - attach_workspace:
          at: .
      - run:
          name: Install dotnet tools
          command: dotnet tool restore
      - run:
          name: Download zen binaries
          command: |
            dotnet tool install --global Cake.Tool
            dotnet cake --target DownloadLibraries
      - run:
          name: Restore NuGet Packages
          command: dotnet restore
      - run:
          name: Run E2E Tests
          command: |
            dotnet test "Aikido.Zen.Test.End2End/Aikido.Zen.Test.End2End.csproj" \
              --configuration Release \
              --output "TestResults" \
              --logger "console;"
      - store_test_results:
          path: TestResults
      - store_artifacts:
          path: TestResults

workflows:
  test_on_pr:
    jobs:
      - checkout_code
      - e2e_test:
          requires:
            - checkout_code
          matrix:
            parameters:
              dotnet_version: ["8.0"]
