version: 2.1

orbs:
  win: circleci/windows@5.0

jobs:
  checkout_code:
    docker:
      - image: cimg/base:2022.08
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths:
            - .

  e2e_test:
    parameters:
      dotnet_version:
        type: string
    executor:
      name: win/default
    environment:
      ROOT_DIR: ${CIRCLE_WORKING_DIRECTORY}
      USE_NAT: true
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Restore NuGet Packages (.NET Framework)
          command: |
            nuget restore "sample-apps/DotNetFramework.Sample.App/DotNetFramework.Sample.App.csproj"
            nuget restore "Aikido.Zen.DotNetFramework/Aikido.Zen.DotNetFramework.csproj"
      - run:
          name: Install Dependencies (.NET Core)
          command: dotnet restore
      - run:
          name: Build .NET Framework Projects
          command: |
            $msbuildPath = "C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\MSBuild.exe"
            & $msbuildPath "sample-apps/DotNetFramework.Sample.App/DotNetFramework.Sample.App.csproj" /p:Configuration=Debug /p:Platform="Any CPU" /t:Rebuild
            & $msbuildPath "Aikido.Zen.DotNetFramework/Aikido.Zen.DotNetFramework.csproj" /p:Configuration=Debug /p:Platform="Any CPU" /t:Rebuild
      - run:
          name: Build .NET Core Projects
          command: |
            dotnet build "Aikido.Zen.DotNetCore/Aikido.Zen.DotNetCore.csproj" --configuration Debug --framework net<< parameters.dotnet_version >>
      - run:
          name: Run E2E Tests
          command: |
            dotnet test "Aikido.Zen.Test.End2End/Aikido.Zen.Test.End2End.csproj" \
              --configuration Debug \
              --verbosity detailed \
              --logger "console;verbosity=detailed" \
              --no-build \
              --no-restore

workflows:
  test_on_pr:
    jobs:
      - checkout_code
      - e2e_test:
          requires:
            - checkout_code
          matrix:
            parameters:
              dotnet_version: ["6.0", "7.0", "8.0"]
