version: 2.1

jobs:
  checkout_code:
    docker:
      - image: cimg/base:2022.08
    steps:
      - checkout
      - run:
          name: Generate Package References Checksum
          command: bash ./.circleci/generate-packages-checksum.sh
      - persist_to_workspace:
          root: .
          paths:
            - .
            - packages.txt
            - packages.checksum

  e2e_test:
    parameters:
      dotnet_version:
        type: string
    machine:
      image: ubuntu-2404:current
    steps:
      - checkout
      - run:
          name: install dotnet
          command: |
            sudo add-apt-repository -y ppa:dotnet/backports
            sudo apt-get update
            sudo apt-get install -y dotnet-sdk-<< parameters.dotnet_version >>
      - attach_workspace:
          at: .
      - run:
          name: Install dotnet tools
          command: dotnet tool restore
      - run:
          name: Run E2E tests via Cake script
          command: |
            dotnet tool install --global Cake.Tool
            # Set terminal size to avoid logger failure
            # https://github.com/dotnet/msbuild/issues/11213
            stty cols 120
            stty rows 50
            dotnet cake --target=TestE2E --configuration=Release --framework=<< parameters.dotnet_version >>

workflows:
  test_on_pr:
    jobs:
      - checkout_code
      - e2e_test:
          requires:
            - checkout_code
          matrix:
            parameters:
              dotnet_version: ["9.0"]
