version: 2.1

orbs:
  win: circleci/windows@5.0

jobs:
  checkout_code:
    docker:
      - image: cimg/base:2022.08
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths:
            - .
  e2e_test:
    parameters:
      dotnet_version:
        type: string
    executor:
      name: win/default
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Install Dependencies
          command: dotnet restore
      - run:
          name: Run E2E Tests
          command: dotnet cake --target=TestE2E --configuration=Release --framework=net<< parameters.dotnet_version >> --verbosity=diagnostic

workflows:
  test_on_pr:
    jobs:
      - checkout_code
      - e2e_test:
          requires:
            - checkout_code
          matrix:
            parameters:
              dotnet_version: ["6.0", "7.0", "8.0"]
