version: 2.1

orbs:
  win: circleci/windows@5.0

jobs:
  checkout_code:
    docker:
      - image: cimg/base:2022.08
    steps:
      - checkout
      - run:
          name: Generate Package References Checksum
          command: bash ./.circleci/generate-packages-checksum.sh
      - persist_to_workspace:
          root: .
          paths:
            - .
            - packages.txt
            - packages.checksum

  e2e_test:
    parameters:
      dotnet_version:
        type: string
    executor:
      name: win/default
    environment:
      ROOT_DIR: ${CIRCLE_WORKING_DIRECTORY}
      USE_NAT: true
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Check for Cache
          command: |
            try
            {
              $no_nuget = (ls ~\.nuget\packages).Length -eq 0
              $exit_code = if ($no_nuget) { 1 } else { 0 }
              exit $exit_code
            }
            catch
            {
              exit 1
            }
      - run:
          name: Restore NuGet Packages
          command: |
            dotnet restore --use-lock-file
            nuget restore
          when: on_fail
      - save_cache:
          name: Cache Nuget Packages
          key: nuget-{{ checksum "Directory.Packages.props" }}-{{ .Environment.CACHE_VERSION }}
          paths:
            - "~/.nuget"
          when: always
      - run:
          name: Build
          command: |
            $msbuildPath = "C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\MSBuild.exe"
            & $msbuildPath
      - run:
          name: Run E2E Tests
          command: |
            dotnet test "Aikido.Zen.Test.End2End/Aikido.Zen.Test.End2End.csproj" `
              --configuration Release `
              --verbosity detailed `
              --logger "console;verbosity=detailed"

workflows:
  test_on_pr:
    jobs:
      - checkout_code
      - e2e_test:
          requires:
            - checkout_code
          matrix:
            parameters:
              dotnet_version: ["6.0", "7.0", "8.0"]
