name: Publish NuGet Packages

on:
    release:
        types: [created]

jobs:
    publish:
        runs-on: windows-2022
        timeout-minutes: 30

        env:
            DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
            DOTNET_CLI_TELEMETRY_OPTOUT: true
            CAKE_NUGETAPIKEY: ${{ secrets.NUGETAPIKEY }}

        steps:
            - uses: actions/checkout@v4

            - uses: actions/cache@v3
              with:
                  path: |
                      ~/.nuget/packages
                      ~/.local/share/NuGet/v3-cache
                  key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj', '**/*.props', '**/*.targets') }}
                  restore-keys: |
                      ${{ runner.os }}-nuget-

            - name: Setup .NET
              uses: actions/setup-dotnet@v3
              with:
                  dotnet-version: |
                      4.6.1
                      4.7.2
                      4.8.2
                      6.0.x
                      7.0.x
                      8.0.x

            - name: Add msbuild to PATH
              uses: microsoft/setup-msbuild@v2
              with:
                  vs-version: "[17.2,19.0)"

            - name: Install Cake Tool
              run: dotnet tool install --global Cake.Tool

            - name: Run Cake Script to Build and Pack
              run: dotnet cake build.cake --target=CreatePackages

            - name: Publish NuGet Packages
              run: |
                  for %%f in (artifacts\*.nupkg) do (
                    dotnet nuget push %%f --api-key ${{ secrets.NUGETAPIKEY }} --source https://api.nuget.org/v3/index.json
                  )
